#!/bin/sh
set -e

sudo systemctl stop trafficserver || :
sudo install ./src/traffic_server/.libs/traffic_server /usr/bin/
sudo systemctl start trafficserver
sudo systemctl --no-pager status trafficserver
